title: XOST Studio
description: >-
  A futuristic software and gaming brand — building the next-gen digital experiences.
baseurl: "" 
url: "https://xost-studio.github.io"

remote_theme: pages-themes/cayman@v0.2.0


include:
  - _includes
plugins:
  - jekyll-favicon  # Not required but helpful


author:
  name: XOST-Studio
  email: waleednaeem133@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

---

## 👤 Meet the Founder
> **[Muhammad Waleed](about/muhammad‑waleed.md)** – Founder, Lead Developer & Creative Engineer.

---

## 📢 Stay Connected
- GitHub: <https://github.com/XOST‑Studio>
- Instagram: @xost.studio
- Email: hello@xoststudio.com

_Ready to collaborate? Drop us a line and let’s shape the future together!_

---

© 2025 XOST Studio. All rights reserved.


exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
