title: XOST Studio
description: >-
  A futuristic software and gaming brand — building the next-gen digital experiences.
baseurl: "" 
url: "https://xost-studio.github.io"

remote_theme: pages-themes/hacker@v0.2.0


author:
  name: XOST-Studio
  email: waleednaeem133@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
